version: '3'
services:
  petclinic:
    build: .
    ports:
      - "9966:9966"
    networks:
      - myTSANet
    links:
      - tsa
  tmc:
    image: wm_912/terracotta_tmc:4.3.3.1.10
    ports:
      - "9889:9889"
    networks:
      - myTSANet
    links:
      - tsa
  tsa:
    image: wm_912/terracotta_server:4.3.3.1.10
    hostname: tsa
    networks:
      myTSANet:
        aliases:
          - tsa
    ports:
      - "9510:9510"
      - "9530:9530"
    volumes:
      - $PWD/../server/terracotta_data_single/:/terracotta_data
networks:
  myTSANet:
