version: '3'
services:
  petclinic:
    build:
      context: .
      args:
        - ehcache_version=2.10.3.1.12
        - terracotta_version=4.3.3.1.10
    ports:
      - "9966:9966"
    networks:
      - myTSANet
    environment:
      - TSA_URL=tsa1:9510,tsa2:9510
      - ehcache_version=2.10.3.1.12
      - terracotta_version=4.3.3.1.10
    links:
      - tsa1
      - tsa2
  tmc:
    image: wm_912/terracotta_tmc:4.3.3.1.10
    ports:
      - "9889:9889"
    networks:
      - myTSANet
    links:
      - tsa1
      - tsa2
  tsa1:
    image: wm_912/terracotta_server:4.3.3.1.10
    hostname: tsa1
    networks:
      myTSANet:
        aliases:
          - tsa1
    ports:
      - "9510:9510"
      - "9530:9530"
    environment:
      - TC_SERVER1=tsa1
      - TC_SERVER2=tsa2
    volumes:
      - $PWD/../server/terracotta_data1/:/terracotta_data
  tsa2:
    image: wm_912/terracotta_server:4.3.3.1.10
    hostname: tsa2
    networks:
      myTSANet:
        aliases:
          - tsa2
    ports:
      - "9610:9510"
      - "9630:9530"
    environment:
      - TC_SERVER1=tsa1
      - TC_SERVER2=tsa2
    volumes:
      - $PWD/../server/terracotta_data2/:/terracotta_data
networks:
  myTSANet:
