version: '3'
services:
  tmc:
    image: wm_912/terracotta_tmc:4.3.3.1.10
    ports:
      - "9889:9889"
    links:
      - tsa
  tsa:
    image: wm_912/terracotta_server:4.3.3.1.10
    ports:
      - "9510:9510"
      - "9530:9530"
    volumes:
      - $PWD/../server/terracotta_data_single/:/terracotta_data
